defaults:
    - _self_
    - override hydra/hydra_logging: disabled
    - override hydra/job_logging: disabled

seed: 0
exp_name: ex4
run_id: ??? # decided during execution

#train_episodes: ${train_episodes}
#max_episode_steps: ${max_episode_steps}
test_episodes: 50
random_episodes: 10

save_video: false
save_logging: true
save_model: true
silent: false # print restuls to the terminal if false
use_wandb: true

env_parameters:
  continuous: true
  gravity: -9.81
  enable_wind: false
  wind_power: 15
  turbulence_power: 1.5

env_name: 'LunarLander-v2'

agent_name: dqn
max_episode_steps: 1000
train_episodes: 2000
grad_clip_norm: 1

batch_size: 128 # 512
buffer_size: 50000 # 500000
hidden_dims: [64, 64]
glie_b: 200
tau: 0.001
lr: 6.3e-4 # 5e-5

# policy: 'MlpPolicy'
gamma: 0.99
target_update_interval: 250
train_freq: 4
gradient_steps: -1
exploration_fraction: 0.12
exploration_final_eps: 0.1
policy_kwargs: "dict(net_arch=[256, 256])"

run_suffix: 0
# ref: https://stackoverflow.com/questions/65104134/disable-file-output-of-hydra
hydra:
    output_subdir: null
    run:
        dir: .
